#ifndef SPLINESERIESCHART_GLOBAL_H
#define SPLINESERIESCHART_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SPLINESERIESCHART_LIBRARY)
#  define SPLINESERIESCHART_EXPORT Q_DECL_EXPORT
#else
#  define SPLINESERIESCHART_EXPORT Q_DECL_IMPORT
#endif

#endif // SPLINESERIESCHART_GLOBAL_H
