#ifndef ROUNDPROGRESS_GLOBAL_H
#define ROUNDPROGRESS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROUNDPROGRESS_LIBRARY)
#  define ROUNDPROGRESS_EXPORT Q_DECL_EXPORT
#else
#  define ROUNDPROGRESS_EXPORT Q_DECL_IMPORT
#endif

#endif // ROUNDPROGRESS_GLOBAL_H
